language: python
python: "3.5"

env:
  matrix:
    - TOXENV=py27-flake8
    - TOXENV=py33-flake8
    - TOXENV=py34-flake8
    - TOXENV=py35-flake8
    - TOXENV=checkdocs
    - TOXENV=jshint

install:
  - pip install tox
script:
  - tox -e $TOXENV
