language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
env:
  - TOXENV=flake8
matrix:
  include:
    - { python: 3.6, env: TOXENV=jshint }
    - { python: 3.6, env: TOXENV=readme }

install:
  - pip install tox-travis
script:
  - tox
