language: python

# Use container based infrastructure
sudo: false

env:
  matrix:
    - TOXENV=flake8

install:
  - pip install tox
  - npm install -g jshint
script:
  - tox -e $TOXENV
  - jshint djangocms_maps
