language: python

# Use container based infrastructure
sudo: false

env:
  matrix:
    - TOXENV=flake8

install:
  - pip install tox
  - pip install collective.checkdocs pygments
  - npm install -g jshint
script:
  - tox -e $TOXENV
  - jshint djangocms_maps
  - python setup.py -q sdist && python setup.py checkdocs
