language: python
python: "3.5"

# Use container based infrastructure
sudo: false

env:
  matrix:
    - TOXENV=py27-flake8
    - TOXENV=py33-flake8
    - TOXENV=py34-flake8
    - TOXENV=py35-flake8

install:
  - pip install tox
  - pip install collective.checkdocs pygments
  - npm install -g jshint
script:
  - tox -e $TOXENV
  - jshint djangocms_maps
  - python setup.py -q sdist && python setup.py checkdocs
